"""Document export — PDF / DOCX / TXT from GeneratedDocument."""
from __future__ import annotations

import io
import os
from typing import Literal

from app.schemas.agents import GeneratedDocument


TAG_LABELS = {
    "verified_fact": "[VERIFIED FACT]",
    "legal_source": "[LEGAL SOURCE]",
    "ai_generated": "[AI-GENERATED]",
    "needs_review": "[NEEDS REVIEW]",
    "placeholder": "[PLACEHOLDER — fill in]",
}

DISCLAIMER = (
    "\n\n---\n"
    "DISCLAIMER: This document was generated by Nyaya, an AI-assisted legal "
    "information platform. It does NOT constitute legal advice and does NOT "
    "replace consultation with a qualified legal professional. All legal "
    "provisions cited are from a DEMO knowledge base and must be verified "
    "against authoritative sources before use.\n"
)


def _plain_text(doc: GeneratedDocument) -> str:
    """Render the document as plain text."""
    lines: list[str] = []
    lines.append(f"{'=' * 60}")
    lines.append(doc.title.upper())
    lines.append(f"{'=' * 60}\n")

    for section in doc.sections:
        tag = TAG_LABELS.get(section.tag, "")
        lines.append(f"--- {section.heading} {tag} ---")
        lines.append(section.body)
        if section.notes:
            lines.append(f"  Note: {section.notes}")
        lines.append("")

    if doc.legal_sources:
        lines.append("--- SOURCES ---")
        for src in doc.legal_sources:
            parts = [src.title]
            if src.section:
                parts.append(f"§{src.section}")
            if src.court:
                parts.append(src.court)
            if src.demo_data:
                parts.append("(DEMO DATA)")
            lines.append(f"  • {' — '.join(parts)}")
        lines.append("")

    if doc.needs_review:
        lines.append("--- NEEDS REVIEW ---")
        for item in doc.needs_review:
            lines.append(f"  ⚠ {item}")
        lines.append("")

    vr = doc.validation_report
    lines.append(
        f"Validation: {vr.citations_verified}/{vr.citations_checked} citations verified"
    )

    lines.append(DISCLAIMER)
    return "\n".join(lines)


def export_txt(doc: GeneratedDocument) -> bytes:
    """Export as UTF-8 text."""
    return _plain_text(doc).encode("utf-8")


def export_pdf(doc: GeneratedDocument) -> bytes:
    """Export as PDF using ReportLab."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            Paragraph,
            SimpleDocTemplate,
            Spacer,
        )
    except ImportError:
        # Fallback: return text as PDF-like bytes
        return export_txt(doc)

    buf = io.BytesIO()
    pdf = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "DocTitle", parent=styles["Title"], fontSize=16, spaceAfter=12
    )
    heading_style = ParagraphStyle(
        "SectionHead", parent=styles["Heading2"], fontSize=12, spaceAfter=6,
        spaceBefore=12,
    )
    body_style = ParagraphStyle(
        "SectionBody", parent=styles["Normal"], fontSize=10, leading=14,
        spaceAfter=6,
    )
    tag_style = ParagraphStyle(
        "TagLabel", parent=styles["Normal"], fontSize=8, textColor="grey",
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=8, textColor="grey",
        leading=10, spaceAfter=6, spaceBefore=12,
    )

    story: list = []
    story.append(Paragraph(doc.title, title_style))
    story.append(Spacer(1, 12))

    for section in doc.sections:
        tag = TAG_LABELS.get(section.tag, "")
        story.append(Paragraph(f"{section.heading} <font size=8 color='grey'>{tag}</font>", heading_style))
        # Replace newlines with <br/> for PDF
        body_html = section.body.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        body_html = body_html.replace("\n", "<br/>")
        story.append(Paragraph(body_html, body_style))
        if section.notes:
            story.append(Paragraph(f"<i>Note: {section.notes}</i>", tag_style))

    if doc.legal_sources:
        story.append(Paragraph("SOURCES", heading_style))
        for src in doc.legal_sources:
            parts = [src.title]
            if src.section:
                parts.append(f"§{src.section}")
            if src.demo_data:
                parts.append("(DEMO DATA)")
            story.append(Paragraph(f"• {' — '.join(parts)}", body_style))

    if doc.needs_review:
        story.append(Paragraph("NEEDS REVIEW", heading_style))
        for item in doc.needs_review:
            story.append(Paragraph(f"⚠ {item}", body_style))

    story.append(Paragraph(DISCLAIMER.replace("\n", "<br/>"), disclaimer_style))

    pdf.build(story)
    return buf.getvalue()


def export_docx(doc: GeneratedDocument) -> bytes:
    """Export as DOCX using python-docx."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
    except ImportError:
        return export_txt(doc)

    document = Document()

    # Title
    title_para = document.add_heading(doc.title, level=0)

    for section in doc.sections:
        tag = TAG_LABELS.get(section.tag, "")
        document.add_heading(f"{section.heading}", level=2)
        if tag:
            tag_para = document.add_paragraph()
            tag_run = tag_para.add_run(tag)
            tag_run.font.size = Pt(8)
            tag_run.font.color.rgb = RGBColor(128, 128, 128)

        for line in section.body.split("\n"):
            document.add_paragraph(line)

        if section.notes:
            note_para = document.add_paragraph()
            note_run = note_para.add_run(f"Note: {section.notes}")
            note_run.font.size = Pt(9)
            note_run.font.italic = True

    if doc.legal_sources:
        document.add_heading("Sources", level=2)
        for src in doc.legal_sources:
            parts = [src.title]
            if src.section:
                parts.append(f"§{src.section}")
            if src.demo_data:
                parts.append("(DEMO DATA)")
            document.add_paragraph(f"• {' — '.join(parts)}")

    if doc.needs_review:
        document.add_heading("Needs Review", level=2)
        for item in doc.needs_review:
            document.add_paragraph(f"⚠ {item}")

    # Disclaimer
    disclaimer_para = document.add_paragraph()
    disclaimer_run = disclaimer_para.add_run(DISCLAIMER.strip())
    disclaimer_run.font.size = Pt(8)
    disclaimer_run.font.color.rgb = RGBColor(128, 128, 128)

    buf = io.BytesIO()
    document.save(buf)
    return buf.getvalue()


def export_document(
    doc: GeneratedDocument,
    fmt: Literal["pdf", "docx", "txt"] = "pdf",
) -> tuple[bytes, str, str]:
    """Returns (content_bytes, content_type, filename_extension)."""
    if fmt == "pdf":
        return export_pdf(doc), "application/pdf", ".pdf"
    elif fmt == "docx":
        return (
            export_docx(doc),
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            ".docx",
        )
    else:
        return export_txt(doc), "text/plain; charset=utf-8", ".txt"
